### ISSUE TITLE
Transition SASS implementation from libsass to dart sass

### ISSUE THREAD

**Issue by abutterworth** [edx/frontend-build#111]
We should update frontend build to use the Dart implementation of SASS (npm: `sass`) instead of the C++ implementation called Libsass (bindings via npm:`node-sass`) in `sass-loader`. See the webpack docs: https://webpack.js.org/loaders/sass-loader/.

Dart SASS is now the primary implementation for SASS (https://sass-lang.com/blog/announcing-dart-sass, https://sass-lang.com/dart-sass). The libsass implementation is in maintenance mode.

- Webpack docs now recommend using dart sass with sass-loader (and show how) https://webpack.js.org/loaders/sass-loader/
- the dart sass npm package is called just sass https://github.com/sass/dart-sass#from-npm
- libsass is missing new features like @use (see the compatibility line at the top of the docs here https://sass-lang.com/documentation/at-rules/use)

**Comment by adamstankiewicz** [comment]
This issue is now resolved on v5.2.1.
