### ISSUE TITLE
Proposal: support a gitignored local dev config file to replace(or supplant) .env.development

### ISSUE THREAD

**Issue by binodpant** [edx/frontend-build#140]
See this for a ref conversation: https://github.com/edx/frontend-app-learner-portal-enterprise/pull/149#discussion_r534325437

Similar to how we do the private.py in edx-enterprise and other python repoes, this would be nice so we don't accidentally check in changes to .env.development files

**Comment by adamstankiewicz** [comment]
Issue resolved.
